// The Muslimah Faceless Business Blueprint for Beginners
// Content model. Rendered by build.js
module.exports = [

{front: true},

{copyright: [
  "First edition. Published [YEAR] by KMB Digital Consulting.",
  "Copyright \u00a9 [YEAR] Karrie Noor Chariton. All rights reserved.",
  "No part of this workbook may be reproduced, distributed, resold or transmitted in any form without the prior written permission of the author. This book is sold for the personal use of the purchaser. No resale, reproduction or redistribution rights are granted with purchase.",
  "The information in this book is offered in good faith and for general guidance. It is not legal, financial or tax advice. Business requirements differ by country and by state; consult a qualified professional about your own situation.",
  "No income claim is made or implied anywhere in this book. What you earn depends on your work, your market and your circumstances.",
  "Some links in this book are affiliate links. If you buy through them I may receive a small commission at no extra cost to you. I only recommend tools I use myself.",
  "[YOUR CONTACT OR WEBSITE]"
]},

{toc: [
  ["1", "Set Your Intention"], ["2", "Create Your Vision"], ["3", "Build Your Brand"],
  ["4", "Pick a Platform"], ["5", "Staying Faceless"], ["6", "Optimising Your Profile"],
  ["7", "The Five Signals \u2014 What Replaces a Face"], ["8", "Is This Halal?"],
  ["9", "What You'll Offer"], ["10", "Pricing & Income Goals"], ["11", "Your Freebie"],
  ["12", "Setting Up Your Shop"], ["13", "Automate With Email"], ["14", "Building Community"],
  ["15", "Faceless Marketing \u2014 Instagram"], ["16", "Your First Sale"],
  ["17", "Business Basics"], ["18", "It's Go Time"],
  ["", "The Templates That Go With This Book"],
  ["", "About Karrie Noor"], ["", "What To Do Next"]
]},

{h1: "How This Book Works"},
{p: "This book takes you from a blank page to a faceless online business that is actually live. Your intention, your vision, your niche, your brand, the privacy decisions that keep you comfortable, the trust-building work that replaces a photograph, the questions to settle before you take money, your offer, your price, your freebie, your email system, your community, and the content that puts it all in front of people."},
{p: "It is built to be written in, not just read. Every chapter ends with lines for you to fill in before you move on. Skipping the fill-ins is the fastest way to finish the book and still not have a business."},
{p: "Work through it in order once. After that, come back to whichever chapter you need. Inshallah."},
{note: "A word on how this is written. Nothing in here assumes you want to be on camera. Where a platform is named, it is named as an option, not an instruction. Where I have a number, I give you the number. Where I do not, I tell you that instead."},

{pb: true},
{h1: "Chapter 1", sub: "Set Your Intention"},
{p: "Before anything else — before the niche, the name, the plan — set your intention. In Islam, intention (niyyah) comes first. It is what turns an ordinary action into something with purpose. Every deed is judged by the intention behind it."},
{p: "So before you build anything, sit with this honestly. Why are you really doing this? Who is it for, beyond just you? What would it mean for your family, your deen, your sense of purpose, if this actually worked?"},
{p: "There is no wrong answer here, and you do not have to make it sound noble. “I want my own money” is an intention. “I want to stop asking” is an intention. “I want something that is mine” is an intention. Write the true one, not the presentable one."},
{prompt: "My intention. Write it as a statement you could return to on a hard day. Something like: “I am building this so that…”", lines: 6},
{h2: "A short dua before you begin"},
{p: "Take a moment, however that looks for you, and ask Allah to put barakah in the work ahead — in your time, your effort, and what comes from it. Write your own words below, or come back to this page whenever you need to reset your intention."},
{prompt: "My dua", lines: 5},

{pb: true},
{h1: "Chapter 2", sub: "Create Your Vision"},
{p: "Now dream. Not carefully, not realistically. What do you actually want?"},
{p: "As a midlife woman, take off the hat you are wearing right now — mother, wife, daughter, caregiver, employee — just for these few minutes. What do you want? Do not think yet about how you would get it."},
{p: "Allah can give you anything He wills. Do not shrink your vision down to what feels achievable before you have even let yourself imagine the full thing. You can always narrow it later. That comes next. But it starts here, big."},
{prompt: "Dream big — let it be too much. If nothing was in your way (money, time, fear), what would you build? What would your days look like? Who would you be helping? Write without editing yourself.", lines: 10},

{h2: "Know your why"},
{p: "Without a why, you will give up when it gets hard. And it will get hard — not dramatically, just quietly, on a Tuesday when you are tired and nothing has happened yet."},
{p: "Ask yourself these, and answer them honestly rather than impressively:"},
{b: ["What first attracted me to the idea of building something online?",
     "What do I most want this work to do in the world?",
     "How would this change my life?",
     "What would the people I love gain from it?"]},
{p: "Dig deeper than the first answer. The first answer is usually the one you think you are supposed to give. The businesses that last solve a real problem from a real place."},
{prompt: "My why, in my own words", lines: 6},

{h2: "Choose your niche"},
{p: "A niche is simply the specific area you focus on. It is what makes your content recognisable and lets you attract people who are actually interested, rather than everyone and no one."},
{p: "Why it matters: when you have a clear niche you build a following with focused interest, which makes it far easier to sell to them later. It builds credibility, because you become known for something. And it makes you memorable in a very crowded room."},
{p: "A niche that works sits at the intersection of four things:"},
{b: ["What you are genuinely curious about — the thing you would read about anyway",
     "What you already know something about — and you do not have to be an expert",
     "A real problem you can solve for someone",
     "Enough people who want that problem solved, and would pay to have it solved"]},
{p: "Most niches sit under a few large umbrellas. A few to get you thinking: health (physical, mental, spiritual); wealth (money, business, career); relationships (marriage, parenting, family); home and lifestyle; faith and personal growth."},
{p: "Then narrow. “Health” is not a niche. “Gentle strength training for women over fifty” is a niche. “Faith” is not a niche. “Helping new Muslim women through their first Ramadan” is a niche."},
{prompt: "Ideas for my niche — write three to five. Narrow later.", lines: 6},
{prompt: "The one I am starting with, and why", lines: 4},

{h2: "Choose your dream customer"},
{p: "Every product solves a problem for a specific person. The clearer that person is in your mind, the easier every other decision in this book becomes — what to write, what to sell, what to charge."},
{p: "Get concrete. Age range. Life stage. What she does all day. What she is struggling with. What she would need from you to feel seen rather than sold to."},
{p: "If you have ever done related work — even informally, even as a volunteer, even for free for a friend — think about who you wanted to serve then. That is usually the clearest answer to who your dream customer already is."},
{p: "A few questions to get you moving: How old is she? Where does she live? What does she do? What is she responsible for? What does she want that she has not said out loud? What does she need from you?"},
{example: "“I want to help midlife Muslim women build online businesses without showing their faces.”"},
{prompt: "My dream customer, in a few sentences. Give her a name if it helps.", lines: 8},

{pb: true},
{h1: "Chapter 3", sub: "Build Your Brand"},
{p: "Your brand is bigger than colours and fonts. It is how you make people feel, what you are known for, and the story only you can tell. Two people can copy the same aesthetic. Nobody can copy your story."},

{h2: "The four decisions"},
{b: ["Tone — how you sound. Calm, direct, warm, plainspoken, funny, serious.",
     "Style — how things look. Simple, warm, modern, minimal, rich, bright.",
     "Values — what you stand for, and what you will not do for money.",
     "Your story — the real reason you started, in your own words."]},
{p: "That third one matters more than people expect. What you will not promote, will not sell, will not work on — that is judgement, and judgement only comes from having seen things go wrong. Most people hide their standards because they think they will lose customers. You will not. Standards are how the right person recognises you."},
{prompt: "My tone — three words", lines: 2},
{prompt: "My style — three words", lines: 2},
{prompt: "My values — and one thing I will not do", lines: 4},

{h2: "Visual identity"},
{p: "Your visual identity is everything from your profile image to the fonts and colours in your content. Consistency is what makes a brand recognisable. It is doing, for free, the job a face would otherwise do."},
{p: "Start a Pinterest board before you decide anything. Save whatever feels like the brand you are picturing — colours, fonts, layouts, moods. You do not have to know why yet. Just collect. Pay attention to what repeats."},
{link: "Canva", n: "\u2014 design, templates, colour palettes"},
{tip: "Search “colour palette” or “font pairing” on Pinterest or inside Canva. Coolors.co will also build you a palette in seconds. Remember that less is more — you want two fonts and three or four colours, not twelve."},
{p: "Set a timer for this. An hour, no more. Fonts and colours are one of the easiest places to disappear into and call it work."},
{prompt: "My Pinterest board name or link", lines: 2},

{h2: "Tone of voice"},
{p: "Your tone of voice is how you express yourself in words — not just which words, but your sentence lengths, your punctuation, whether you use emojis, whether you are formal or plain. It should be consistent everywhere: your content, your emails, your product, your shop."},
{p: "The simplest test there is: read it out loud. If you would never say it to someone sitting at your kitchen table, rewrite it."},
{prompt: "We sound… (three words or phrases)", lines: 3},
{prompt: "We never sound… (three words or phrases)", lines: 3},

{h2: "Your faceless persona"},
{p: "Your persona is what comes through in your writing, your images and your voice, without your face. It is built from your personality, your story, and a consistent visual identity that does not include a photograph of you."},
{p: "Share real parts of yourself while keeping your privacy. People connect with real people, and they can do that without seeing you. Storytelling is how that connection actually happens — which is what the next chapters are about."},
{prompt: "Three stories I could tell. They do not need to be polished. Just get the raw material down — three stories connected to who you want to help and why.", lines: 9},

{pb: true},
{h1: "Chapter 4", sub: "Pick a Platform"},
{p: "Before you name anything or write a single bio, decide where you are actually going to show up. Pick a platform based on where your dream customer already spends time, not where you personally like scrolling."},
{h2: "A rough guide"},
{b: ["Instagram — skews younger and more millennial. Visual, fast-moving, rewards volume.",
     "Facebook — often a stronger fit for Gen X and over-fifties. Groups are still powerful.",
     "YouTube — long-form, works across ages, and searchable years later.",
     "Pinterest — search-based rather than social. Slow to start, compounds for years, pairs well with a blog or a shop.",
     "A newsletter — no algorithm at all. You own the list."]},
{p: "Your platform choice should match what you are selling and how. A blog paired with Pinterest is a different strategy from a fast-moving Instagram presence. Neither is better. They are just different trades: speed against longevity, reach against ownership."},
{p: "Start with one. Show up consistently there before you add a second. Two platforms done badly is worse than one done properly, and it is roughly four times the work."},
{prompt: "My starting platform, and why", lines: 4},
{prompt: "The platform I am deliberately not starting with (and when I might)", lines: 3},

{pb: true},
{h1: "Chapter 5", sub: "Staying Faceless"},
{p: "This is the chapter nobody writes, and it is the one you will need most. Every other book tells you how to build trust without a face. None of them tell you how to actually keep the face out of it once money is involved."},
{p: "Decide these things once, now, before anything is public. Undoing them later is possible but tedious, and some of it you cannot undo at all."},

{h2: "What counts as faceless for you"},
{p: "Faceless is not one setting. It is a line, and the line is different for everybody. Some women mean no photographs of their face. Some mean no real name. Some mean nobody from their masjid, their workplace or their family finding this at all."},
{p: "Work out which one you mean before you decide anything else, because it changes every answer below."},
{prompt: "My line. Be specific about what I will and will not have public.", lines: 5},

{h2: "Your name"},
{p: "You have three options and they are all legitimate. Your real name. A pen name. Or a business name with no personal name attached at all."},
{b: ["Your real name builds trust fastest and is the hardest to undo. If you ever want to write under it elsewhere, it compounds.",
     "A pen name protects you and still lets you be a person. Pick one you can answer to out loud, and check nobody else is already using it.",
     "A business name only is the most private, and the slowest to build a following behind, because people follow people."]},
{warn: "If you sell anything, a real legal name may still appear somewhere \u2014 on a tax registration, a payment account, or a book's copyright page. A pen name protects you from a casual search, not from a determined one. Know which you are buying."},
{prompt: "The name that goes public, and where my real name may still appear", lines: 4},

{h2: "Your address"},
{p: "Buying a domain, registering a business or sending marketing email can all put an address into a public record. Your home address is not the one you want there."},
{b: ["Turn on domain privacy when you register a domain. It is usually free or a few pounds a year, and it hides your details from public lookup.",
     "Use a PO box, a virtual business address or a mail-forwarding service for anything that has to be public.",
     "Check what your email platform puts in the footer. Anti-spam law requires a physical address on marketing email \u2014 make sure it is not your kitchen."]},
{prompt: "The address I will use publicly, and where I still need to sort this out", lines: 3},

{h2: "The video call question"},
{p: "Sooner or later a client, a collaborator or a podcast host will ask to see your face. Decide your answer now, in writing, so you are not improvising under pressure."},
{p: "You do not owe anybody an explanation, and a short answer works better than a long one. Something like: \u201cI keep my work camera-free \u2014 happy to do this by voice or in writing.\u201d Said plainly, most people simply say fine."},
{p: "If someone pushes after that, they have told you something useful about what working with them would be like."},
{prompt: "My answer, written out, so I can copy and paste it", lines: 4},

{h2: "Payments and paperwork"},
{b: ["Check what appears on a customer's bank statement when they buy from you. Payment processors let you set this \u2014 make it your business name, not yours.",
     "Keep a separate business email address. Never send business from a personal one you use with family.",
     "If you register a company, check what your country makes public. Some publish a director's name and address; some do not. Look before you file, not after."]},

{h2: "The accounts that already exist"},
{p: "You almost certainly have old profiles with your face on them, under your real name, that a curious person could find in a minute. You do not have to delete anything. But do this once, deliberately, in one sitting:"},
{check: ["Search your own name and see what comes up",
         "Search your new brand name and see whether it leads back to you",
         "Decide which old accounts get locked down, renamed, or left alone",
         "Set the ones you keep to private, or tidy the photo and header",
         "Write down which ones you consciously decided to leave public, and why"]},
{tip: "Do this in one session and then stop. This task expands to fill whatever time you give it, and it feels productive while producing nothing. An hour, once."},
{prompt: "What I found, and what I am changing", lines: 5},

{pb: true},
{h1: "Chapter 6", sub: "Optimising Your Profile"},
{p: "Before you name your page, find out how people actually search for what you do. Type a few phrases into the search bar on your chosen platform and see what comes up — the accounts, the wording, the phrases that repeat. Those real phrases are your keywords, and they should shape the name and bio you land on next."},
{prompt: "Keywords I found", lines: 4},

{h2: "Naming your page"},
{p: "Pick something clear about who you help. Avoid naming yourself after a single trend or format — a name tied too tightly to one thing makes it harder to evolve later."},
{p: "You have two layers, and mixing them up causes trouble. There is your name — the person. And there is your publication — the thing people follow and subscribe to. They do not have to be the same, and on a search-driven platform the publication name usually does more work, because nobody is looking for you by name yet."},
{prompt: "Name ideas", lines: 4},

{h2: "Writing your bio"},
{p: "Your bio is the first real impression, and most people waste it describing themselves. Include four things: one clear line about what you do, who it is for, how you help them, and a next step."},
{p: "The three-second test: show your profile to somebody who does not know you. Ask them what the page is about, who it is for, what it posts, and why somebody would follow. If they cannot answer all four, it is too vague."},
{prompt: "Bio draft", lines: 6},
{prompt: "My one next step (the link, the freebie, the action)", lines: 2},

{pb: true},
{h1: "Chapter 7", sub: "The Five Signals — What Replaces a Face"},
{p: "A face is a shortcut. When someone sees you, they make a fast judgement — she seems real, she seems like she knows what she is talking about, she seems like me. That happens before they read a word."},
{p: "Take the face away and you do not lose trust. You lose the shortcut. So you build the same trust the slower way, on purpose, with five signals."},
{p: "Most faceless accounts feel cold because three or four of these are missing — not because there is no photo."},

{h2: "Signal 1 — Lived experience"},
{p: "The thing you have actually been through, standing behind what you say. This is the signal people most often think they do not have, and almost always do."},
{p: "It does not have to be decades. It can be the eighteen months you just spent solving a problem badly and then finally solving it properly. Recency counts for more than people expect — the woman one step ahead of your reader is often more useful to her than the woman ten steps ahead, because she still remembers what the first step felt like."},
{example: "You spent four Ramadans trying to keep a routine and failing, and in the fifth you worked out what had actually been going wrong. You are not a scholar. You are exactly the right person to tell someone in her first year, because you know the specific way it falls apart."},
{p: "What it is not: credentials. Nobody buying a $27 guide is checking your qualifications. They are checking whether you sound like you have been where they are."},
{p: "The mistake here is waiting. Lived experience is not a thing you arrive at; it is a thing you are currently accumulating. If you wait until you feel expert, you will wait past the point where you were most useful."},
{ws: ["Consistency is important when you are building a business.", "I rebuilt my business from scratch three times before I understood that the rebuilding was the problem."]},
{p: "The difference between those two lines is not writing skill. It is that the second one could only have been written by someone who did it."},
{prompt: "Three things I know now that I did not know when I started", lines: 5},
{prompt: "A problem I have personally solved — badly first, then properly", lines: 4},

{h2: "Signal 2 — Receipts"},
{p: "Showing the work when you cannot show the worker. A receipt does not have to be impressive. It has to be real, and it has to be yours."},
{p: "A dated screenshot beats an adjective every time. If you do not have the number, say so and give the one you do have. A reader forgives a small number instantly. She never forgives a vague one."},
{p: "What counts as a receipt when you have not made any money yet:"},
{b: ["A before and after of your own work — the first version and the current one.",
     "A dated screenshot of anything real. Fourteen subscribers is a receipt. “A growing community” is not.",
     "A message someone sent you, with permission and their name removed.",
     "Your own process, photographed or screen-recorded mid-way through. Unfinished work is evidence that work is happening.",
     "The thing itself. A product that exists is a receipt for the claim that you can make things."]},
{p: "What does not count: adjectives, stock photos of laptops and coffee, and anyone else’s results — including results from the course you bought. Borrowed proof reads as borrowed, and it costs you more than having none."},
{example: "“I grew fast” is an adjective. “Sixty-one subscribers in seven weeks, and here is the week it stalled” is a receipt — and the stall is the part that makes it believable."},
{warn: "If you genuinely have no receipts yet, the first one is your own result, earned in public. Start the thing, post the starting number, and post it again in thirty days. That sequence is a receipt even if the number barely moves."},
{prompt: "One receipt I could screenshot this week", lines: 3},
{prompt: "The number I am starting from today — whatever it is", lines: 3},

{h2: "Signal 3 — A recognisable package"},
{p: "Looking the same for long enough that people learn you. Not because it is beautiful — because repetition does, for free, the job a face would have done."},
{p: "The whole specification fits on a line: two fonts, three or four colours, one layout you repeat, and one format people come to expect from you."},
{example: "Someone scrolling sees a navy square with a line of serif text across the middle. She does not read the handle. She already knows it is you, because it is the ninth time this month she has seen that square. That recognition is the entire mechanism, and it is doing what a photograph of your face would have done."},
{p: "The mistake is redesigning. It feels productive, it is genuinely enjoyable, and it resets the counter to zero every time. The recognition only starts once you stop changing things."},
{warn: "Pick today, then use it for ten pieces without changing anything. You are allowed to revisit it after ten, not before. Write the date on the line below so the decision is already made when the urge arrives — and it will arrive around piece four."},
{prompt: "Font 1 / Font 2 / My colours / The date I am allowed to revisit this", lines: 5},

{h2: "Signal 4 — Your actual voice"},
{p: "Sounding like one specific human being. Faceless is not voiceless — you can keep your face out of it entirely and still be completely present."},
{p: "Voice is mostly a matter of removal. Most people write a perfectly good sentence, then add a layer of business language on top of it because they think that is what selling sounds like. It is not. It is what nervousness sounds like."},
{p: "Three tests, applied to any line you are unsure about:"},
{b: ["Would I say this out loud, to a friend, in this order?",
     "Is there a word in here I have never used in my life?",
     "Does it name something specific, or is it true of everybody?"]},
{ws: ["In today’s fast-moving digital landscape, consistency is key.", "I skipped two weeks in Ramadan and nothing bad happened."]},
{ws: ["Unlock your full potential and start your journey today.", "You do not need another course. You need to finish the one you bought in March."]},
{p: "Notice that the strong version in both is shorter, more specific, and slightly riskier. That last part is not incidental. A line that could not possibly offend anyone generally does not reach anyone either."},
{p: "On AI, plainly: use it for the parts that carry no judgement — sorting, tidying, giving you twenty options to react to. The moment it starts supplying what you think, you have handed over the only part that was working."},
{prompt: "One line of mine, rewritten by hand", lines: 4},

{h2: "Signal 5 — Consistency you can hold"},
{p: "A number you can keep in a bad week. Not a schedule somebody else designed for a life that is not yours."},
{p: "Pick the number you could keep on your worst week, not your best one. Everybody picks their best-week number. Then they miss it, and the missing is what makes people quit — not the workload."},
{example: "Two posts a week, held for a year, is a hundred and four pieces and an audience that knows when to expect you. Daily posting for six weeks is forty-two pieces and a quiet account by August. The second one felt far more serious at the time."},
{p: "You will miss it. Someone will get sick, work will go sideways, or Ramadan will arrive and reorganise everything. That is not a failure of the plan; it is a fact the plan has to survive."},
{p: "So decide the recovery rule now, while nothing has gone wrong: when you miss, you do not spend a week feeling bad about it and you do not start over. You open the plan and start again on the next one. Missing costs you one unit. Guilt costs you a month."},
{prompt: "My number / my unit (posts, hours, actions) / the worst week I could still do this in", lines: 4},
{prompt: "My recovery rule, written before I need it", lines: 3},

{h2: "The Five Signals audit"},
{p: "Score yourself honestly. There is no version of this where all five start high."},
{audit: ["Lived experience", "Receipts", "A recognisable package", "Your actual voice", "Consistency you can hold"]},
{p: "Do not try to fix all five. Take your lowest score and work on it for thirty days. If everything scored low, start with the package — it is the fastest to change, it costs nothing, and it is the one that stops you starting over."},
{prompt: "My lowest signal, and what I will actually do about it for thirty days", lines: 5},
{p: "You do not need a face. You need to be findable, and the same, for long enough that somebody recognises you. That is the whole job."}
,
{pb: true},
{h1: "Chapter 8", sub: "Is This Halal?"},
{p: "This chapter is not a fatwa. I am not qualified to give you one and you should not take one from a workbook. What I can give you is the list of questions worth asking, and a place to write down the answers you settle on — so that when a decision comes up at speed, you already know where you stand."},
{p: "Most of us get this backwards. We build the whole thing, then a question surfaces about how the money works, and by then we are too invested to want the answer. Ask early, while changing course still costs you nothing."},
{warn: "Where something here is genuinely contested, take it to someone qualified — your local imam, a scholar you trust, or a specialist in Islamic finance. Ask a specific question, not a general one. “Is affiliate marketing halal?” gets you a lecture. “I would earn a commission when someone buys this software through my link — is that permissible?” gets you an answer."},

{h2: "1. The thing itself"},
{p: "Start with the product, not the marketing. Is what you are selling permissible, and does it help someone do something permissible?"},
{b: ["What does this product actually help someone do?",
     "Would I be comfortable if the person I most respect knew exactly what I sell and how?",
     "Does it require the buyer to do anything I would not do?",
     "Am I selling knowledge I actually have, or knowledge I am hoping to have by the time they ask?"]},
{p: "That last one catches more people than the others. Selling a guide to something you have not done is not a fiqh problem so much as a truthfulness problem — but it becomes one the moment the sales page implies experience you do not have."},
{prompt: "What I sell, and why I am satisfied it is permissible", lines: 4},

{h2: "2. Riba — where interest quietly enters a small business"},
{p: "You do not need a loan to run into this. It arrives through ordinary tools, usually by default."},
{b: ["Payment plans you offer. Splitting a price over three months at the same total is not interest. Adding a fee for paying late, or charging more for the instalment option than the one-off, is where it changes.",
     "Buy-now-pay-later at checkout. Many platforms enable these automatically. Check what is switched on, and read how the provider makes its money.",
     "Business credit cards and overdrafts. The ordinary route to funding a first product is interest-bearing by design.",
     "The account the money sits in. Interest paid to you on a business current account is the same question from the other direction.",
     "Financing your own tools. Subscriptions billed annually with a finance option attached are easy to click through without noticing."]},
{tip: "This is the one to ask about before you take a single payment, because it is built into the checkout settings you are about to choose. Turning a feature off on day one costs nothing. Turning it off after ninety customers have used it is a refund policy problem."},
{prompt: "My standard on payment plans, BNPL and the account I bank into", lines: 4},

{h2: "3. Affiliate income"},
{p: "Affiliate links are a normal part of how online businesses earn, and there is nothing inherently wrong with being paid for a genuine referral. The questions are about what you are referring people to, and whether they know."},
{b: ["Do I use this product myself, currently, and would I recommend it with no commission attached?",
     "Is the company’s core business something I want to earn from? Alcohol, pork, gambling, conventional lending and adult content are the obvious ones — but a company can also be clean in its product and objectionable in where its money goes.",
     "Am I disclosing the link clearly, every time, in a way a reader would actually notice?",
     "Would I still recommend this if a better free option existed — and does one?"]},
{p: "My own rule, for what it is worth: I only link to things I pay for and use, I say plainly that it is an affiliate link, and I will not take a commission from a company whose money I would not want in my own account. You are welcome to set a stricter line. Set it in writing now, because the first time a company offers you a good rate for something you have never used, you will want a rule rather than a judgement call."},
{prompt: "My affiliate standard — what I will and will not link to", lines: 5},

{h2: "4. How you sell"},
{p: "The marketing is where most of this actually gets decided, because it is where the pressure to exaggerate lives."},
{b: ["No income claims. Not yours, not a screenshot of someone else’s. If you did earn it, saying so implies the reader will too.",
     "No invented scarcity. A deadline that is real is fine. A timer that resets when the page reloads is a lie told in code.",
     "No fear you manufactured. Naming a problem someone already has is service. Inventing one so they buy is not.",
     "No results you cannot evidence. “This is what I did” is honest. “This is what you will get” usually is not.",
     "No testimonials you shaped. Edit for length, never for meaning."]},
{example: "“I made $4,000 in my first month” is a claim, even with a disclaimer under it. “Here is the exact system I used — what you earn depends on your work and your market” is the same information without the promise."},
{prompt: "Something I have seen marketed in a way I would not copy — and what I will do instead", lines: 4},

{h2: "5. Who you work with"},
{p: "As you grow, other people’s money and other people’s brands attach themselves to yours. Decide the rule before the offer arrives, because the offer will arrive when you need the money."},
{b: ["Brands I will not take sponsorship from, whatever the fee.",
     "Collaborations I will not do, and the reason — so I can say it kindly and without a debate.",
     "Clients I will refuse, if I do service work.",
     "What I do when I find out afterwards that a company I promoted does something I object to."]},
{p: "That last one is not hypothetical. It happens to everyone eventually. Having decided in advance that you will pull the link, say so publicly and take the loss, makes it a ten-minute job instead of a week of agonising."},
{prompt: "My lines — who I will not take money from", lines: 4},

{h2: "6. Zakat on what you earn"},
{p: "Business income and business assets are zakatable, and the rules are not the same as for personal savings. What counts, when the year turns, and how stock or receivables are treated are genuine technical questions with genuine technical answers — and they are not mine to give you."},
{p: "What you can do now, before there is anything to calculate: keep the business money separate from your own, and keep a record from the first sale. Reconstructing a year of mixed transactions in month eleven is miserable, and the usual result is that people estimate high out of guilt or low out of exhaustion. Neither is what you wanted."},
{b: ["A separate account for business income and business spending, from the first payment.",
     "A date you have set as your zakat anniversary, written down.",
     "A record of income and expenses, however simple — a spreadsheet is enough at this stage.",
     "One question prepared for someone qualified, once there is a real number to ask about."]},
{prompt: "My zakat date, where my business money sits, and how I am tracking it", lines: 4},

{h2: "Your standards, on one page"},
{p: "Write the short version here. Not the reasoning — the decisions. This is the page you come back to when something arrives in your inbox that pays well and feels off."},
{check: ["I have decided what I will and will not sell",
         "I have checked what my checkout has switched on by default",
         "I have a written affiliate standard",
         "I have a marketing line I will not cross",
         "I know who I will not take money from",
         "My business money is separate and I have a zakat date",
         "I have one question ready for someone qualified"]},
{prompt: "The one question I am going to ask, and who I am going to ask", lines: 3},
{p: "Then get on with it. Scrupulousness that stops you from ever starting is its own problem — the aim is a business you can be answerable for, not a business you never build."}

];
