module.exports = [

{pb: true},
{h1: "Chapter 9", sub: "What You'll Offer"},
{p: "Now decide what you are actually going to sell. The rule is simple: your offer solves a real problem for the dream customer you named in Chapter 2. Not a topic. A problem."},
{p: "Digital products are the usual starting point, and for good reason — no inventory, no shipping, no postage, and you make the thing once. But before you create anything, make sure the problem is real and that people are already looking for an answer to it."},

{h2: "Market research — five ways to find the real problem"},
{p: "You are not guessing here. You are looking for evidence that people already want this solved."},
{b: ["Keyword research. Use a free keyword tool and search phrases around your niche. You are looking for volume — evidence that real people type this in. Write down every phrase that surprises you.",
     "Social listening. Read the comments on videos and posts in your niche. Not the posts — the comments. That is where people say what they are actually struggling with, in their own words. Copy those words down exactly.",
     "Surveys and polls. If you already have any audience at all, even fifteen people, ask them directly. One question beats ten.",
     "Forums and communities. Reddit, Facebook groups, Quora. Look for the same question being asked over and over by different people. Repetition is demand.",
     "Your own experience. You have almost certainly lived the problem you are about to solve. That is not cheating — it is the fastest research there is, and it is the only kind nobody else has."]},
{link: "Keyword research tool", n: "\u2014 for checking real search demand"},
{tip: "You can use AI to speed the first pass up, not to replace it. Try: “What are the ten most searched questions about [my niche]?” or “What digital products already exist for [my audience], and what do they cover?” Then go and verify what it tells you. It will be confidently wrong at least once."},
{prompt: "The problem I keep seeing — in their words, not mine", lines: 5},
{prompt: "Keywords and phrases worth remembering", lines: 5},

{h2: "Your first product"},
{p: "Your first product answers one problem. Not a topic, not everything you know, not the whole of your niche — one problem, solved properly."},
{p: "Formats that work for a first product: a guide, a template, a checklist, a planner, a short course, a workbook, a swipe file, a set of scripts."},
{p: "Look at what already exists in your niche and ask two questions: what is missing, and what would I have wanted when I was at the start? The gap between those two answers is usually your product."},
{example: "A planner exists, but it does not track the one thing you actually needed to track. A guide exists, but it assumes you already have an audience. A course exists, but it is forty hours long and your reader has two."},
{prompt: "My first product idea — the one problem it solves, and the format", lines: 5},
{p: "Once you are live, pay attention to the other problems people mention while they are using your first product. Those become your next ones, and you will not have to go looking for them."},

{h2: "Your “I help” statement"},
{p: "Before you make anything, write one sentence: I help [who] to [do what] without [the thing they dread]. It is not a slogan and it does not go on your profile unless you want it to. Its job is to stop you building a product for nobody in particular."},
{example: "“I help working mothers plan a week of school lunches without cooking anything new.” “I help new Muslim women get through their first Ramadan without feeling like a guest.” “I help beginners sell their first digital product without showing their face.”"},
{p: "If you cannot finish the sentence, the problem is not your writing. It is that you have not narrowed the person yet. Go back to Chapter 2."},
{prompt: "I help ______ to ______ without ______", lines: 4},

{h2: "Actually making it"},
{p: "Two routes. Neither is better — they cost different things."},
{b: ["Build it from scratch. Open a design tool, start from a blank template or a free one, and write the whole thing yourself. Costs time, costs nothing else, and every word is yours.",
     "Start from a template or a ready-made product you have a licence to modify. Costs money, saves weeks, and puts you in front of a customer faster. This is a normal and legitimate way to start — as long as the licence actually permits it."]},
{warn: "If you buy something to modify and sell, read the licence before you buy, not after. Licences differ enormously. Some permit editing and resale. Some permit editing for personal use only. Some permit resale but not the transfer of resale rights onward. “PLR” and “commercial use” are marketing words, not legal ones — the terms of the specific listing are what bind you. If the licence is not published, assume the answer is no."},
{p: "The same applies to design templates, fonts, stock photos and stock video. A free template inside a design tool is usually free to use commercially only once you have substantially customised it — check the platform’s own licensing page, because they do change."},
{link: "Where I get my templates", n: "— [your affiliate link]"},
{link: "Where I get my images and stock video", n: "— [your affiliate link]"},

{h2: "The build, step by step"},
{check: ["Write the content first, in a plain document. No design, no colours, no fonts — just the words and the order.",
         "Cut it by a third. Your first product is almost certainly too long.",
         "Choose your format: PDF guide, workbook, template pack, checklist, short course.",
         "Design it, using your brand colours and your two fonts from Chapter 3. Nothing else.",
         "Add the fill-in space if it is a workbook. People finish things they can write in.",
         "Export as a PDF and open it on your phone. Most of your buyers will.",
         "Give one honest person a copy before you sell it, and ask them what confused them."]},
{tip: "Do not design first. Designing a beautiful product around thin content is the most enjoyable way there is to waste two weeks, and you will not notice you are doing it."},
{prompt: "My product — format, rough length, and the date it will be finished", lines: 4},
{p: "Write a real date on that last line. Not “soon.” A product with no finish date is a hobby, and hobbies do not reach anyone."},

{pb: true},
{h1: "Chapter 10", sub: "Pricing & Income Goals"},
{p: "Do not overthink this part. Pick a price. It is always easier to start lower and raise it than to start high and walk it back."},
{p: "A simple approach: launch at an introductory price, use that window to collect a few honest testimonials, then raise the price once you have real proof behind it."},

{h2: "The three bands"},
{b: ["Low ticket, roughly £10–£50 or $10–$50. Easy to say yes to. Needs volume to add up.",
     "Mid ticket, roughly $100–$500. The balance of margin and ease. This is where most first real income comes from.",
     "High ticket, $1,000 and up. Fewer sales needed, but a much higher trust bar to clear — and trust takes time you do not have yet."]},
{p: "For a first product with no audience, mid ticket is usually the fastest route to a meaningful number. Four people at $250 is $1,000. Thirty-seven people at $27 is also $1,000 — but you need thirty-seven, and you do not know thirty-seven people yet."},

{h2: "Four questions to price against"},
{b: ["What does this actually change for the person who buys it?",
     "What are similar products selling for?",
     "What did it cost you in time, tools and thought to create?",
     "What price would feel fair to the woman you are selling to — not to you?"]},
{prompt: "My starting price, and why", lines: 4},

{h2: "Your first goal"},
{p: "This does not have to be an income goal yet. If showing up online is new to you, a more useful first goal is a habit — a posting rhythm, a number of conversations, a simple repetition you are building toward."},
{example: "“I will publish one thing a week and have two real conversations a week.” That repetition is what everything else, including income, eventually gets built on."},
{p: "Whatever you choose, break it down the same way: thirty days, a quarter, a year. Growth is rarely even. Most of it compounds later, so do not expect month one to look like month twelve."},
{prompt: "My first goal — income, audience, or rhythm", lines: 3},
{prompt: "30-day goal", lines: 2},
{prompt: "Quarter goal", lines: 2},
{prompt: "Year goal", lines: 2},

{pb: true},
{h1: "Chapter 11", sub: "Your Freebie"},
{p: "A freebie, or lead magnet, is something genuinely useful you give away in exchange for an email address."},
{p: "Why it matters more than it looks:"},
{b: ["List building. Everyone who signs up is someone you can reach directly, without an algorithm deciding whether you are allowed to.",
     "Trust. Giving something valuable away before asking for anything is the fastest way to be taken seriously.",
     "Security. If a platform suspends your account tomorrow — and it happens — your list is still yours. Your followers are not.",
     "Automation. This is the piece that lets the business work while you are at your job, asleep, or with your family."]},

{h2: "What makes a good one"},
{b: ["It solves one specific, pressing problem — not a whole topic.",
     "It gives a real win on its own, even if she never buys anything.",
     "It previews what your paid product does at a bigger scale. A taste, not the whole meal.",
     "It can be used in a few minutes. Nobody finishes a forty-page freebie."]},
{p: "Formats that work: a mini guide, a checklist, a template, a short list, a single worksheet, a swipe file, a short training."},
{tip: "Sign up for a few freebies in your niche to see what others are doing — not to copy them, but to notice what made you hand over your email and what made you close the tab."},
{prompt: "My freebie idea — the one problem it solves", lines: 4},
{prompt: "Why someone would want it enough to give me their email", lines: 3},

{h2: "The two emails you need before you launch anything"},
{p: "A freebie confirmation email, which delivers the freebie and sounds like you. And a purchase confirmation email, which delivers the paid product, thanks them properly, and invites them to reply."},
{p: "Keep both short and warm and in your own voice. Skip anything that reads like a sales script you would not actually say out loud."},
{prompt: "The first line of my freebie email", lines: 3},

{pb: true},
{h1: "Chapter 12", sub: "Setting Up Your Shop"},
{p: "You need one place where your freebie, your paid product and your email list all live, so people can find you and buy from you without extra steps."},
{p: "A single all-in-one platform — email, a simple checkout, basic automation — is enough to start. You do not need five different tools stitched together, and stitching them together is a very effective way to spend three weeks not launching."},

{h2: "What to set up, in this order"},
{b: ["A landing page for your freebie, with a signup form",
     "A simple checkout page for your first paid product",
     "One automated email that delivers each, the moment someone signs up or buys",
     "Nothing else"]},
{link: "Systeme.io", n: "\u2014 the all-in-one I use for this"},
{p: "Whichever platform you choose, look for free tutorials from the platform itself. Those change often enough that a screenshot in a book goes stale within months."},
{warn: "Test it yourself before you tell anybody. Sign up for your own freebie with a personal email address. Buy your own product. Click every link. A dead link on launch day burns the only traffic you will get, and you will not find out for a week."},
{prompt: "The platform I am using, and the date my checkout will be tested", lines: 3},

{pb: true},
{h1: "Chapter 13", sub: "Automate With Email"},
{p: "This is the chapter that turns a set of pieces into a business that runs without you sitting at it."},
{p: "An email flow is simply a sequence of emails that sends automatically, on a schedule, to everyone who joins your list. You write it once. It works for everyone who arrives afterwards, whether that is next week or next year."},

{h2: "The two confirmation emails"},
{p: "Before any flow, you need these. Someone signs up for your freebie and receives it immediately with a short note from you. Someone buys your product and receives it immediately with a short note from you. That is it."},
{p: "Write them the way you would write to one person, because that is how they will be read."},
{prompt: "Freebie confirmation — subject line and first line", lines: 4},
{prompt: "Purchase confirmation — subject line and first line", lines: 4},

{h2: "Your first email flow"},
{p: "You need one flow to start: the one that goes to people who opted in for your freebie. There is no single correct way to write it, but this shape works:"},
{b: ["Email 1, immediately. Deliver the freebie. Say a genuine thank you. Tell her what is coming.",
     "Email 2, one to two days later. A story or a useful idea. No pitch at all.",
     "Email 3, one to two days later. More value, and the first gentle mention of what you sell.",
     "Email 4, one to two days later. A clear, honest invitation to buy — what it is, who it is for, what it costs."]},
{h2: "Four templates to start from"},
{p: "Change every word of these if you want to \u2014 they are scaffolding, not scripture. But they give you something to react to, which is faster than a blank page. Nothing in them promises a result I have not seen, and nothing in them should promise a result you have not seen either."},

{tpl: ["Email 1 \u2014 sent immediately", "Subject: Here it is \u2014 your [freebie name]",
 "Assalamu alaikum [first name],",
 "Here is the [freebie name] you asked for: [LINK]",
 "It should take you about ten minutes. If you only do one thing in it, do [the single most useful step] \u2014 that is the part that actually moves something.",
 "Over the next few days I am going to send you three more emails. One is a story about how I got this wrong for years. One is a practical thing you can use. And the last one tells you about [product name], in case it is useful.",
 "If you ever want to reply, do. I read them.",
 "[Your name]"]},

{tpl: ["Email 2 \u2014 one to two days later", "Subject: The part nobody tells you",
 "Assalamu alaikum [first name],",
 "[Open with one specific, true moment. Not a lesson \u2014 a scene. Where you were, what you were doing, what you believed at the time.]",
 "[What you believed then, and why it was wrong.]",
 "[What you know now. Keep it to one idea.]",
 "Here is why I am telling you this: [connect it directly to the problem she is trying to solve].",
 "Nothing to click today. Just something to sit with.",
 "[Your name]"]},

{tpl: ["Email 3 \u2014 one to two days later", "Subject: [The specific, useful thing]",
 "Assalamu alaikum [first name],",
 "Quick one today, because I think this will save you time.",
 "[The useful thing. A method, a shortcut, a checklist, a question to ask yourself. Give it away properly \u2014 do not hold the good part back.]",
 "[One sentence on how to use it this week.]",
 "By the way \u2014 this is a small piece of what is inside [product name]. If you want the whole thing, I will tell you about it properly tomorrow.",
 "[Your name]"]},

{tpl: ["Email 4 \u2014 one to two days later", "Subject: [Product name] \u2014 what it is and who it is for",
 "Assalamu alaikum [first name],",
 "I want to tell you about [product name], and then I will leave you alone about it.",
 "It is for [the specific person] who wants [the specific outcome] and is stuck on [the specific problem].",
 "Inside: [three things she gets, plainly stated].",
 "It costs [price]. It takes about [time] to work through.",
 "It is not for you if [be honest \u2014 name who this genuinely will not help]. I would rather you kept your money than bought the wrong thing.",
 "If it is for you: [LINK]",
 "And if it is not, stay on this list anyway. I will keep sending useful things.",
 "[Your name]"]},

{tip: "Notice what email four does not do. It does not promise an income figure. It does not say how fast. It names who it is not for. That last move sells more than any urgency line, because it is the only thing in her inbox that sounds like a person telling the truth."},

{warn: "A note on how you write these. Do not promise income you have not made. Do not imply results you cannot screenshot. Do not write “I made X while doing Y” unless you did. It is the fastest way to lose a reader who is smarter than the sales page she has been sent before — and your reader has been sent a lot of them."},
{p: "Write these the way you would talk to someone you actually wanted to help. Then test your own flow by signing up for it yourself before you send anyone else through it."},
{prompt: "Email 1 — one sentence of it, in my voice", lines: 3},
{prompt: "Email 2 — the story I would tell", lines: 4},
{prompt: "Email 3 — the useful thing", lines: 3},
{prompt: "Email 4 — the honest invitation", lines: 4},
{p: "Later, once this one is working, you may want a second flow for people who have bought — to welcome them properly and, eventually, to introduce whatever you make next. Not yet."},

{pb: true},
{h1: "Chapter 14", sub: "Building Community"},
{p: "A faceless brand still needs a real community. Without one you have content, not a business. And building one without showing your face is far more possible than people tell you — as long as you show up consistently and let people see the parts of you that are not your face: your thinking, your story, your standards, your work."},

{h2: "Consistency — the number, plainly"},
{p: "Consistency means showing up at least once a day. In the early stage, posting more than once a day tells the algorithm you are an active account and tells your audience you are reliable. Over time, that reliability is what turns into trust."},
{p: "A working rule of thumb when starting out on Instagram: two to three Reels a day, and roughly six to eight Stories. As your following grows you can drop to one Reel a day and lean more on Stories."},
{p: "If that number makes your stomach drop, read it again as what it is — the pace that grows an account fastest, not a moral obligation. Batch it. Sit down once a week and make the week. What you cannot do is disappear for a fortnight and come back expecting the same reach."},
{prompt: "The number I am committing to, and the day I will batch it", lines: 3},

{h2: "What actually builds it"},
{b: ["Consistency. Showing up on a rhythm you can sustain, not a burst you will burn out on. Frequency matters less than never disappearing.",
     "A cohesive look. So people recognise your content before they read your name. This is Signal 3 from Chapter 7, doing its job.",
     "Your real story. Anyone can copy an aesthetic. Nobody can copy why you started, what it cost, and what changed.",
     "Serving before selling. Especially at the start, when no trust exists yet.",
     "Genuine replies. Answer comments and messages like a person, not a brand. Ask a question back."]},

{h2: "Serve first, sell later"},
{p: "Serving is selling, eventually. But in the early months your only job is to be useful. People do not care how your day is going. They care what you can do for them. Once that lands properly, everything else gets easier."},
{p: "What providing value actually looks like: answering the questions your reader is already asking; researching the problem she has and giving her a real solution; showing her a problem she had not named yet and then solving it; sharing the specific thing you know that saves her time."},

{h2: "Behind the scenes, without a face"},
{p: "Genuine glimpses of the real you, none of which require showing yourself: a corner of your desk. What you are reading. A screenshot of something that did not work. A meal. The view from where you write. A short note about something that happened this week."},
{p: "These resonate more than staged perfection. You are a real person behind the content, and people need evidence of that — not a photograph of your face."},

{h2: "Your story is the part nobody can copy"},
{p: "This is the most important thing in your branding, and it is easy to miss because it does not look like branding. Anyone can copy your colours. Anyone can copy your fonts, your format, even your hooks. Nobody can copy why you started."},
{p: "Storytelling works because buying decisions are emotional before they are rational. A story lets someone feel something about you before they have decided anything about you. It also does your filtering for you — the right person recognises herself in it and stays; the wrong one scrolls past, which saves you both time."},
{p: "None of this requires your face. It requires specifics. “I struggled at the start” is not a story. “I paid for a course I never opened and told nobody for a year” is."},
{p: "Where the story goes: your captions, your Stories, your emails, your sales pages. Not once — repeatedly, in pieces. Most of your audience has never seen any of it."},
{b: ["Why you started — the actual moment, not the tidy version.",
     "What your life looked like before this.",
     "What you tried that did not work.",
     "What changed, and what it cost you.",
     "What you know now that you wish someone had told you."]},
{prompt: "The moment I started — in specifics, not summary", lines: 6},
{prompt: "Something I tried that did not work, and what it taught me", lines: 5},

{h2: "Replying like a person"},
{p: "Answer comments and messages in the tone you would use with a friend, not the tone of a brand account. Ask a question back — a real one. A reply that ends the conversation is a missed one."},
{p: "Voice notes are worth more than they look. They are unmistakably a person, they take you thirty seconds, and they still show nothing. If you are faceless, an audio reply is the single fastest way to be a human being to someone."},
{p: "Comments build faster bonds than broadcast ever will. Ten real conversations this week will do more than a hundred posts nobody answered."},

{h2: "The words you use for your people"},
{p: "The most overlooked part of community building is the language. The words you use to describe your reader are what make her feel recognised — or make her feel like she is watching someone else’s brand."},
{p: "Pick the words your people already use about themselves, and use them in your captions, Stories and emails. Not a label you invented. The phrase she would type into a search bar at eleven at night."},
{example: "“Camera shy.” “Quietly building.” “Starting late.” “Not a tech person.” “Private.” Any of these lands harder than “entrepreneurs” ever will."},
{warn: "Test it out loud. If a phrase would make you wince to say to a friend in person, it will make her wince to read it. Borrowed community language is worse than none."},
{prompt: "The words my people use about themselves — in their words, not mine", lines: 5},

{h2: "A room of your own"},
{p: "At some point a group of your own beats posting into a feed. A community space gives people somewhere to go, somewhere to talk to each other, and somewhere you do not have to fight an algorithm to be seen. It is also where the people who already trust you become the people who buy from you."},
{p: "Skool is the platform I use for this. It puts a community, a course area and a payment system in one place, which matters when you are one person doing all of it. A free group with real conversation in it beats a paid group with silence in it every single time \u2014 so start free, and charge later if it earns it."},
{link: "Skool", n: "\u2014 community, courses and payments in one place"},
{p: "Do not build the room before anybody is coming, though. An empty room reads as a failed room, and the people who arrive early will leave. Build it when you have people who keep replying. That is the signal."},

{h2: "The tools underneath it"},
{p: "A community needs somewhere for people to land, and something that reaches them without a platform\u2019s permission. That means a landing page, an email list, and a way to take payment."},
{p: "You can stitch this together from four or five separate tools, and many people do. I would not. Every extra tool is another login, another subscription, another thing that breaks quietly at two in the morning. One platform that does landing pages, email automation and checkout together will get you live faster and keep you there."},
{p: "Systeme.io is what I use. Landing pages, email sequences, checkout and automation in a single account, with a free tier that is genuinely usable while you are starting."},
{link: "Systeme.io", n: "\u2014 landing pages, email automation and checkout"},
{tip: "Whatever you choose, set it up once and leave it alone. Rebuilding your tech stack is one of the most convincing forms of procrastination there is, because it genuinely looks like work."},
{prompt: "One way I will show up consistently", lines: 3},

{pb: true},
{h1: "Chapter 15", sub: "Faceless Marketing — Instagram"},
{p: "Instagram is one option, not the only one. If you chose Pinterest or a newsletter in Chapter 4, skim this chapter and come back to it later — nothing here is required."},
{p: "But if Instagram is where your dream customer is, it can be run entirely without your face. This chapter is how."},

{h2: "B-roll footage"},
{p: "B-roll is background footage you use as the video for a reel. You are not in it, or only your hands are. It has become the standard for faceless content, which is good news — it means far less work."},
{p: "Examples: your hands at a keyboard. Pouring tea. Walking. A notebook and pen mid-sentence. Closing a laptop. The sky. A window. Your desk at the hour you actually work, in whatever light that is."},
{tip: "Collect five to seven second clips as you go through your week, or set aside one hour a week to film several. Put them in one album on your phone so they are easy to find when you sit down to make something. Twenty clips will carry you for a month."},
{link: "Stock video and images", n: "\u2014 where I get mine"},
{p: "If filming is not going to happen — and be honest with yourself about that — free stock video from Canva or Pexels will do the same job. Paid libraries exist too, but you do not need one to start."},
{prompt: "Ten b-roll clips I could film this week", lines: 6},

{h2: "Three content pillars"},
{p: "Pillars stop you posting for the sake of posting. Three is enough:"},
{b: ["Educate. Insights, tips, how-to. This is where most of your content lives.",
     "Entertain or inspire. Story, humour, relatability, the honest moment.",
     "Promote. Your offer, with a clear next step."]},
{p: "Most of your content should teach or connect. A much smaller share should point directly at what you sell. If everything promotes, nobody follows."},
{prompt: "My three pillars, in my own words", lines: 4},

{h2: "Saveable and shareable"},
{p: "The goal of most posts is to be one of two things, ideally both."},
{b: ["Shareable — content that makes her think “this is so me” or “this is exactly so-and-so.” Specific enough to your niche that she feels seen, and then sends it on.",
     "Saveable — content valuable enough that she wants to come back to it. Knowledge, a list, a script, a checklist, a piece of guidance."]},
{p: "Both boost engagement far more than a like does, and both are within reach without a face."},

{h2: "The hook"},
{p: "Your hook is the line that stops the scroll. You have roughly three seconds. It needs to be in two places: as on-screen text at the very start of the video, and as the first line of your caption."},
{p: "The on-screen hook earns the watch. The caption hook earns the read — and reading time is watch time."},
{hooks: ["Here’s a shortcut for ___",
         "How to ___ in [x] minutes",
         "The fastest way to ___",
         "The biggest mistake most ___ make",
         "A step-by-step guide to ___",
         "Why ___ will never work for ___",
         "Five things to avoid if you want ___",
         "The biggest misconception about ___",
         "You have been doing ___ wrong",
         "Three rules for ___",
         "My journey from ___ to ___",
         "What I would do differently if I were starting ___ today",
         "The thing nobody tells you about ___",
         "Are you tired of ___? Here is how to fix it",
         "The truth about ___",
         "The dos and don’ts of ___",
         "Stop doing this if you want ___",
         "Five facts you did not know about ___",
         "Three reasons to start ___",
         "The most overlooked way to ___",
         "The best advice I ever got about ___",
         "Behind the scenes of ___",
         "What actually worked for ___",
         "The ultimate checklist for ___",
         "How I got from ___ to ___"]},
{prompt: "Five hooks in my own voice, using my own subject", lines: 7},

{h2: "Call to action"},
{p: "One clear next step per post. Not five. On-screen, a CTA can send people to the caption. In the caption, it asks for one specific action."},
{hooks: ["See caption for more",
         "Comment [word] and I will send you the link",
         "Save this for the next time you need it",
         "Share this with someone who needs it",
         "Tag someone who would relate",
         "Follow for more like this",
         "Head to the link in my bio for the free guide",
         "If you found this useful, save it",
         "Questions? Comment below",
         "Can you relate? Tell me below",
         "What did I miss? Comment below",
         "Steal my whole approach — it is in the caption"]},
{prompt: "Three CTAs I would actually say out loud", lines: 4},

{h2: "Your main message"},
{p: "The point of the post. You can put it on screen as text, or in the caption with a short CTA sending people there. Either works; do not do both badly."},
{p: "If it goes on screen, keep it short enough to read at a glance — crowded text kills a reel faster than a bad hook. If it is longer than a line or two, put it in the caption."},
{p: "Ask yourself: am I giving her something useful? Is this relatable to her specifically? Does it give an idea, a bit of guidance, or a piece of encouragement? It does not have to do all three. It has to do one."},

{h2: "Audio, covers and captions"},
{b: ["Trending audio. Instagram pushes videos using audio it is promoting. Look for the small arrow marking a trend, and prefer audio with fewer than ten thousand uses — by the time something has a million, you are late. Save audio you like as you scroll, then check it is still trending before you use it.",
     "Cover photo. This is what people see on your profile grid. Make sure it shows what the post is about and matches your brand. Either pick a frame that already has your hook on it, or make a cover in Canva at 1080 x 1920.",
     "Caption. Start with your hook. Break it into short lines with spaces — nobody reads a wall of text on a phone. Tell the truth, including the parts that did not work. Use emojis if that is how you talk, and do not if it is not.",
     "Signature. One sentence at the end of every caption telling people who you are and why they would follow you. Save it as a text shortcut on your phone so you are not retyping it forever."]},
{prompt: "My signature line", lines: 3},

{h2: "Hashtags and keywords"},
{p: "Hashtags are not dead, but they are not the whole game either. If you use them, favour less saturated ones — something used fifty to a hundred thousand times will find you more people than something used four million times."},
{p: "Keywords matter more now. Make sure your on-screen text and your caption contain the words your dream customer would actually type. The algorithm reads them, and so does she."},
{prompt: "Ten keywords my reader would actually search", lines: 5},

{h2: "More things worth knowing"},
{b: ["Fonts. Only use text that is easy to read over video. If she has to squint, she scrolls.",
     "Length. Short works. Five to seven seconds is a proven range, and it is far less work.",
     "Filters. Keep it natural. Heavy filters read as trying too hard.",
     "Text placement. Keep text in the centre. The top, bottom and sides get covered by the interface.",
     "Save as you go. Save drafts often, and to your camera roll. Apps lose work.",
     "Schedule ahead. You can make several at once and schedule them. This is how a person with a full-time job does this at all.",
     "Watch your insights. Not likes — saves, shares and comments. Those tell you far more.",
     "Reply to comments. It takes ten minutes and it is the cheapest growth there is.",
     "Be patient. Posts often start moving days or weeks later. Most accounts do not do anything interesting until around the ninety-day mark."]},
{quote: "Fast success builds ego. Slow success builds character."},
{p: "There is nothing wrong with slow growth. Any growth is growth."},

{h2: "How often to post"},
{p: "Consistency means showing up. In the beginning, aim for two to three Reels a day and six to eight Stories a day. That tells the algorithm you are an active account and it tells your audience you are reliable \u2014 and reliability is what builds trust over time."},
{p: "As your following grows you can drop to one Reel a day and lean more on Stories. But at the start, volume is doing two jobs at once: it teaches the platform what you are about, and it teaches you what works, faster than anything else will."},
{p: "If that feels like a lot, it is. Batch it. Film ten clips in one sitting. Write five captions in one sitting. Schedule them. The work is much lighter when it is done in blocks rather than daily from scratch."},
{p: "And if you fall behind \u2014 and you will, at some point \u2014 do not spend a week feeling bad about it. Open the plan and start again the next day. Nobody is keeping score but you."},
{prompt: "My posting rhythm, and how I will batch it", lines: 3},

{h2: "Reels checklist"},
{check: ["A hook in the first three seconds, on screen",
         "One clear CTA — follow, save, share or comment",
         "Trending audio, ideally under ten thousand uses",
         "Real value — teach, inspire, or tell the truth about something",
         "On brand — my fonts, my colours, my tone",
         "Keywords in the on-screen text and the caption",
         "A cover image that says what this is",
         "My signature at the end of the caption"]},

{h2: "Instagram Stories"},
{p: "The people watching your stories are your warmest audience. They already chose you. Stories are where a surprising share of sales actually happen, because you can put a direct link in front of someone who is already interested."},
{p: "Things worth posting: an update on what you are building. A screenshot of a message or a review. A question to your audience. A peek at your desk. What you are working on this week. Something that did not go to plan."},
{p: "Once you have stories worth keeping, save them into Highlights. Useful ones to have: your story and why you started, FAQ, information about your freebie, information about your product, and what people have said about it."},

{h2: "Thirty story ideas when you are stuck"},
{ideas: ["Why you started this",
         "What inspired your brand name",
         "What inspired a particular product",
         "Your core values and why they matter",
         "Your mission, and why she is part of it",
         "A breakthrough a customer had",
         "Your transformation — before, during, after",
         "A hardship and how you got through it",
         "A mistake you made and what it taught you",
         "Something that happened this week",
         "A lesson from this week that helps her too",
         "A common misconception about you or your work",
         "A mindset shift you had",
         "Something that made you laugh",
         "Three tips to help her do X",
         "Five tools that make X easier",
         "Debunk a myth in your field",
         "A statistic that surprised you",
         "A short how-to",
         "A time-saving shortcut",
         "A money-saving shortcut",
         "A Q and A answering the questions you get most",
         "The books worth reading in your field",
         "The podcasts worth hearing",
         "The apps that actually help",
         "Mistakes to avoid in your field",
         "A checklist she can screenshot",
         "What customers say they like best, and why",
         "What life looks like with your product — and without it",
         "An unpopular opinion she would agree with"]},
{prompt: "Five story ideas I could film this week", lines: 6},

{pb: true},
{h1: "Chapter 16", sub: "Your First Sale"},
{p: "Everything up to here was building. This chapter is the part nobody tells you about: the gap between a shop that is live and a human being who has paid you."},
{p: "That gap is almost never closed by more building. It is closed by asking. A product nobody has been told about has not been launched — it has been uploaded."},

{h2: "Your first buyer is already nearby"},
{p: "Almost nobody’s first sale comes from a stranger who found them by chance. It comes from someone who was already within reach: a subscriber, someone who replied to a Story, a woman in a group you are both in, a person who asked you a question two months ago."},
{p: "So before you think about reach, make a list. Not a strategy — a list of actual people."},
{b: ["Everyone on your email list, however small. Twelve people is a list.",
     "Anyone who has replied to you, ever — a comment, a DM, an email.",
     "People in groups or communities where you are genuinely a participant, not a lurker with a link.",
     "Anyone who has asked you the question your product answers.",
     "People you know offline who fit, if you are comfortable with that. You do not have to be."]},
{prompt: "Ten people I could tell about this by name", lines: 10},
{p: "If you cannot fill ten lines, that is not a reason to skip ahead. It is the actual first task: go and have ten conversations before you go and have a launch."},

{h2: "The ask, written down"},
{p: "The reason most first sales do not happen is that the ask never gets made clearly. People hint. They post a pretty graphic and hope. Hoping is not asking."},
{p: "A good ask does four things: names who it is for, says what it changes, gives the price, and tells them exactly what to do next. It takes three sentences and it does not need to be clever."},
{tpl: ["ASK — to someone who already asked you the question",
       "Subject: the thing you asked me about",
       "Hi [name] — you asked me a while back about [their exact question]. I have just finished something that answers it properly: [product name], a [format] that walks through [the one outcome].",
       "It is [price], and it is here: [link].",
       "If it is not the right time, that is completely fine — no need to reply. I just did not want to make the thing and then not tell the person who asked for it."]},
{tpl: ["ASK — to your email list",
       "Subject: I made the thing",
       "I have been working on something for the last few weeks and it is finally done.",
       "[Product name] is for [who] who want to [outcome] without [the thing they dread]. It includes [two or three concrete things]. It takes about [time] to work through.",
       "It is [price] until [date], then [higher price]. You can get it here: [link].",
       "If you have questions before you buy, reply to this email — it comes straight to me."]},
{warn: "Do not apologise in the ask. “Sorry to bother you”, “I know everyone is selling something” and “no pressure at all, honestly” all tell the reader you are not sure it is worth the money. If you are not sure, fix the product. If you are sure, say the price and stop talking."},
{prompt: "My ask, written out in full, in my own words", lines: 8},

{h2: "Tell them more than once"},
{p: "You will feel like you are repeating yourself long before your audience does. On any given day most of your people do not see what you post. Saying it three times is not pushy; it is the minimum required for one person to hear it once."},
{b: ["Before: you are making something, and who it is for. This is not a teaser — it is a filter.",
     "The day: what it is, what it costs, where to get it.",
     "After: the same thing said differently — a question you got, a piece of it, who it is not for."]},
{p: "That last one is the one people skip and it converts the best. Saying plainly who should not buy this is the fastest trust you will ever build."},

{h2: "When someone actually buys"},
{p: "The first sale is a small, strange, enormous thing. Here is what to do in the hour after it."},
{check: ["Check they received the product. Do not assume the automation worked — this is the one time you verify by hand.",
         "Send a short personal message. Not a template. Two sentences from you.",
         "Write down what they bought, when, and where they came from. This is your first piece of real data.",
         "Make the du‘a. Then get back to work — one sale is proof, not a business."]},
{tip: "Leave the automated welcome email in place and send the personal note on top of it. The automation proves the system works. The note proves you do."},

{h2: "The feedback ask"},
{p: "A few days later, ask for feedback — not a testimonial. People freeze when you ask for a testimonial because they think they have to write copy. Feedback is easy to give, and it turns into a testimonial once you have it."},
{p: "Ask three specific questions rather than one open one:"},
{b: ["What were you struggling with before you bought this?",
     "What has changed, if anything?",
     "Was there anything confusing or missing?"]},
{p: "Then ask permission: “Would you mind if I shared part of your answer, with your first name?” Most people say yes. The ones who say no are telling you something useful about the product."},
{prompt: "My feedback questions, and who I will send them to first", lines: 4},

{h2: "If nobody buys"},
{p: "This is the part that decides whether you have a business in a year. Almost everyone’s response to silence is to rebuild the product. It is almost never the product."},
{p: "There are three reasons a launch goes quiet. Work them in this order, because they are in order of likelihood."},
{b: ["Nobody saw it. Far and away the most common. Check your actual numbers — how many people opened the email, how many watched past three seconds. If the number is tiny, you do not have an offer problem, you have a reach problem.",
     "The wrong people saw it. Your content attracted an audience that is not the audience for this product. Common when the content is broad and the product is specific.",
     "The right people saw it and did not believe it. Only now is it the offer — the price, the proof, the promise, or the clarity of what they actually get."]},
{example: "Forty people opened the email and nobody bought. That is a real signal, and it is reason three. Four people opened the email and nobody bought. That is not a signal about your product at all — that is four people."},
{p: "Fix one thing and ask again. Do not rebuild everything, because then you will not know which change did it — and you will have spent another month not selling."},
{prompt: "If it goes quiet: the number I will check first, and the one thing I will change", lines: 5},

{h2: "What the first sale is actually for"},
{p: "It is not the money. At beginner prices the first sale will not change anything about your life."},
{p: "What it gives you is the end of the argument in your own head about whether a stranger will pay you. That question is what stops most people, and it cannot be answered by planning. It can only be answered by one person, once."},
{p: "After that the work is the same work, repeated. Which is genuinely all this is."},
{prompt: "The date I will make my first ask — not the launch date, the day I ask a person", lines: 3},

{pb: true},
{h1: "Chapter 17", sub: "Business Basics"},
{p: "This is not legal advice, and requirements vary by country and by state. Talk to a professional about anything specific to your situation. But a few basics apply broadly, and knowing them early saves a mess later."},
{h2: "If you are setting up formally"},
{b: ["Choose and register a business name. Check availability before you fall in love with one.",
     "Decide on a structure. Many beginners start as a sole trader or a single-member LLC.",
     "Get whatever tax registration your country requires. In the US that is an EIN, free, directly from the IRS website — never pay a third party for one.",
     "Learn your tax obligations early, and get an accountant once you are making real sales. Not before.",
     "Open a separate bank account so personal and business money do not mix. Do this on day one; it costs nothing and saves hours later."]},
{h2: "Your own work"},
{p: "Protect what you make. If you sell something you created, be clear in your terms about what the buyer is allowed to do with it — use it, yes; resell it, no, unless you decide otherwise. Being explicit protects you and prevents an awkward conversation later."},
{prompt: "My next admin step, and the date I will do it", lines: 3},

{pb: true},
{h1: "Chapter 18", sub: "It's Go Time"},
{p: "Once your product, your shop and your first few pieces of content are ready, launch. A launch does not need to be complicated, and almost everything people do to make it feel bigger is delay wearing a costume."},
{h2: "The checklist"},
{check: ["Test your own freebie and checkout, end to end, with a personal email address",
         "Give a short heads-up that something is coming",
         "Share honestly when you go live — what it is, who it is for, and why you made it",
         "Keep pointing at the freebie after launch day. It is your longest-running door in",
         "Wait for real sales before you change your pricing or your messaging"]},
{p: "Slow, steady growth is still growth. There is no version of this that skips the part where you actually start."},
{prompt: "My launch date. Write it down. Tell somebody.", lines: 3},
{p: "You do not need a face. You need to be findable, and the same, for long enough that somebody recognises you."},
{p: "Bismillah. Go and start."},

{pb: true},
{h1: "Bonus", sub: "The Templates That Go With This Book"},
{p: "Every fill-in page in this workbook has a template behind it \u2014 the landing page, the email sequence, the content planner, the freebie layout, the pricing worksheet. Rather than print them in a book you cannot type into, I have put them where you can actually use them."},
{p: "They are free, and they live inside my community. Join, and they are waiting for you:"},
{link: "Free templates \u2014 join the community", n: "\u2014 put your invite link here"},
{p: "What is in there:"},
{b: ["The landing page and opt-in templates, ready to duplicate",
     "The four-email welcome sequence, written out in full",
     "A content planner you can actually fill in",
     "The freebie layout, sized and laid out",
     "The pricing and first-goal worksheets from chapters 8 and 9",
     "Other women doing exactly this, at exactly your stage"]},

{pb: true},
{h1: "About", sub: "Karrie Noor"},
{note: "Draft this after you have read the book through once \u2014 you will know by then which parts of your story the reader actually needs. Keep it to three short paragraphs and one photograph decision. Some things worth including: how long you have been doing this, what you did before, the thing that went wrong that taught you the most, and why this book exists rather than another one."},
{p: "[YOUR ABOUT TEXT \u2014 three paragraphs]"},
{p: "[WHERE TO FIND YOU \u2014 one line]"},

{pb: true},
{h1: "What To Do Next", sub: "If You Want Your First $1,000"},
{p: "You have the whole method now. Intention, vision, niche, brand, the five signals, your offer, your price, your freebie, your shop, your emails, your community and your content. Worked through properly, that is a business."},
{p: "What it does not give you is other people doing it alongside you \u2014 and that is the part that decides whether most women finish."},
{h2: "Two places to go from here"},
{p: "The first is my community. It is where the templates live, where you can ask a question and get an answer from someone who has already hit the same wall, and where you will see what other women at your stage are actually building."},
{link: "Join the community", n: "\u2014 your Skool invite link"},
{p: "The second is my newsletter. One email, written by a person, about the unglamorous specifics of earning your first $1,000 online without showing your face. No pitch most weeks."},
{link: "Subscribe to the newsletter", n: "\u2014 your Substack link"},
{p: "And if you do nothing else, do this: pick one fill-in page from this book that you left blank, and finish it today."},
{quote: "You do not need a face. You need to be findable, and the same, for long enough that somebody recognises you."},

{blank: true}

];
